// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfbeoibslmphyonjlncd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYmVvaWJzbG1waHlvbmpsbmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDU5MjEsImV4cCI6MjA2MTMyMTkyMX0.nmn6xgx_GTQtjBYlZOv_J9dFQwTe_cOqc8LDXsKOE6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);